---
- name: Copy Filebeat configuration.
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/conf.d/{{ filebeat_config_filename }}_filebeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart filebeat




 











  
