---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Filebeat Linux.
  package: name=filebeat state=present
  when: ansible_os_family == 'Windows' or ansible_os_family == 'Debian'

- name: Install Filebeat Windows
  win_chocolately: 
    name: filebeat
    

- include: config.yml
  when: filebeat_create_config

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: yes
