---

- name: Remove existing filebeat
  win_chocolatey:
    name: filebeat
    version: "{{filebeat_version}}"
    state: absent

- name: Remove service
  win_service: name=filebeat state=absent

- name: Ensure filebeat is installed
  win_chocolatey:
    name: filebeat
    version: "{{filebeat_version}}"
    state: present

- name: Ensure filebeat service is started
  win_service: name=filebeat start_mode=auto state=started

- include: config.yml
  when: filebeat_create_config


